apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-secrets" .Release.Name | quote }}
data:
  {{- range $key, $value := .Values.secrets }}
  {{ $key | quote }}: {{ $value | b64enc | quote }}
  {{- end }}
