apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-valheim-server" .Release.Name | quote }}
  labels:
    app: {{ printf "%s-valheim-server" .Release.Name | quote }}
spec:
  selector:
    name: {{ printf "%s-valheim-server" .Release.Name | quote }}
  type: LoadBalancer
  ports:
    - name: play-tcp
      protocol: TCP
      port: 2456
      targetPort: 2456
    - name: play-ucp
      protocol: UDP
      port: 2456
      targetPort: 2456
    - name: query-tcp
      protocol: TCP
      port: 2457
      targetPort: 2457
    - name: query-udp
      protocol: UDP
      port: 2457
      targetPort: 2457
