apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-configs" .Release.Name | quote }}
data:
  {{- range $key, $value := .Values.configs }}
  {{ $key | quote }}: {{ $value | quote }}
  {{- end }}
