apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-csgo-server" .Release.Name | quote }}
  labels:
    app: {{ printf "%s-csgo-server" .Release.Name | quote }}
spec:
  selector:
    name: {{ printf "%s-csgo-server" .Release.Name | quote }}
  type: LoadBalancer
  ports:
    - name: play-tcp
      protocol: TCP
      port: 27015
      targetPort: 27015
    - name: play-ucp
      protocol: UDP
      port: 27015
      targetPort: 27015
    - name: tv-tcp
      protocol: TCP
      port: 27020
      targetPort: 27020
    - name: tv-udp
      protocol: UDP
      port: 27020
      targetPort: 27020
